
def Restock_Shop_Items_0_5(shop):
    shop.Clear()
    shop.AddItem(Item.List["Darts_98"].Copy(True), False)
    shop.AddItem(Item.List["IronDarts_99"].Copy(True), False)
    shop.AddItem(Item.List["MagicDarts_100"].Copy(True), False)
    shop.AddItem(Item.List["ThrowingKnives_101"].Copy(True), False)
    shop.AddItem(Item.List["IronThrowingKnives_102"].Copy(True), False)
    shop.AddItem(Item.List["Arrows_103"].Copy(True), False)
    shop.AddItem(Item.List["IronArrows_104"].Copy(True), False)
    shop.AddItem(Item.List["MagicArrows_105"].Copy(True), False)
    shop.AddItem(Item.List["Javelins_106"].Copy(True), False)
    shop.AddItem(Item.List["IronJavelins_107"].Copy(True), False)
    shop.AddItem(Item.List["CavewoodBow_108"].Copy(True), False)
    shop.AddItem(Item.List["LemonwoodBow_109"].Copy(True), False)

def Restock_Shop_Items_0_8(shop):
    shop.Clear()
    shop.AddItem(Item.List["WeakCuringP_260"].Copy(True), False)
    shop.AddItem(Item.List["WeakHealingP_261"].Copy(True), False)
    shop.AddItem(Item.List["WeakEnergyP_262"].Copy(True), False)
    shop.AddItem(Item.List["WeakStrengthP_263"].Copy(True), False)
    shop.AddItem(Item.List["WeakSpeedP_264"].Copy(True), False)

def Restock_Shop_Items_0_16(shop):
    shop.Clear()
    shop.AddItem(Item.List["StoneKnife_31"].Copy(True), False)
    shop.AddItem(Item.List["StoneShortSword_32"].Copy(True), False)
    shop.AddItem(Item.List["StoneClub_33"].Copy(True), False)
    shop.AddItem(Item.List["StoneMace_34"].Copy(True), False)
    shop.AddItem(Item.List["StoneAxe_35"].Copy(True), False)
    shop.AddItem(Item.List["StoneSpear_36"].Copy(True), False)
    shop.AddItem(Item.List["BronzeKnife_37"].Copy(True), False)
    shop.AddItem(Item.List["BronzeShortSword_38"].Copy(True), False)
    shop.AddItem(Item.List["BronzeClub_39"].Copy(True), False)
    shop.AddItem(Item.List["BronzeMace_40"].Copy(True), False)
    shop.AddItem(Item.List["BronzeAxe_41"].Copy(True), False)
    shop.AddItem(Item.List["BronzeSpear_42"].Copy(True), False)
    shop.AddItem(Item.List["BronzeHammer_43"].Copy(True), False)
    shop.AddItem(Item.List["BronzeRapier_44"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBroadsword_45"].Copy(True), False)
    shop.AddItem(Item.List["BronzeFlail_46"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBardiche_47"].Copy(True), False)
    shop.AddItem(Item.List["BronzeHalberd_48"].Copy(True), False)
    shop.AddItem(Item.List["BronzeGreatsword_49"].Copy(True), False)
    shop.AddItem(Item.List["BronzeGreatMace_50"].Copy(True), False)
    shop.AddItem(Item.List["IronKnife_51"].Copy(True), False)
    shop.AddItem(Item.List["IronShortSword_52"].Copy(True), False)
    shop.AddItem(Item.List["IronMace_53"].Copy(True), False)
    shop.AddItem(Item.List["IronAxe_54"].Copy(True), False)

def Restock_Shop_Items_0_17(shop):
    shop.Clear()
    shop.AddItem(Item.List["LeatherBaldric_120"].Copy(True), False)
    shop.AddItem(Item.List["LeatherArmor_121"].Copy(True), False)
    shop.AddItem(Item.List["BronzeStuddedArmor_122"].Copy(True), False)
    shop.AddItem(Item.List["BronzeChainMail_123"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBreastplate_124"].Copy(True), False)
    shop.AddItem(Item.List["BronzePlate_125"].Copy(True), False)
    shop.AddItem(Item.List["IronStuddedArmor_126"].Copy(True), False)
    shop.AddItem(Item.List["IronChainMail_127"].Copy(True), False)

def Restock_Shop_Items_0_18(shop):
    shop.Clear()
    shop.AddItem(Item.List["CrudeBuckler_139"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBuckler_140"].Copy(True), False)
    shop.AddItem(Item.List["IronBuckler_141"].Copy(True), False)
    shop.AddItem(Item.List["SteelBuckler_142"].Copy(True), False)
    shop.AddItem(Item.List["MagicBuckler_143"].Copy(True), False)
    shop.AddItem(Item.List["CrudeShield_144"].Copy(True), False)
    shop.AddItem(Item.List["BronzeShield_145"].Copy(True), False)
    shop.AddItem(Item.List["IronShield_146"].Copy(True), False)

def Restock_Shop_Items_0_23(shop):
    shop.Clear()
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,1), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,10), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,50), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,1), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,10), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,50), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,1), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,10), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,50), False)
