
def Aerie_1365_MapTrigger_16_27(p):
    if Game.Mode != eMode.TOWN or p.Origin != eCallOrigin.MOVING:
        p.CancelAction = True
        return
    if ChoiceBox("You find a stairway heading down.", eDialogPic.STANDARD, 19, ["Climb", "Leave"]) == 1:
        p.CancelAction = True
        return
    Animation_FadeDown()
    Wait()
    Party.Pos = Location(33,6)
    Party.MoveToMap(TownMap.List["Sanctuary_55"])

def Aerie_1366_MapTrigger_16_19(p):
    if p.Origin == eCallOrigin.SEARCHING: return
    if Game.Mode == eMode.COMBAT:
        return;
    if StuffDone["52_0"] == 0:
        StuffDone["52_0"] = 1
        ChoiceBox("You stand upon the platform before this massive shimmering crystal. Light from within flickers inside the magnificent crystal. As you approach, you swear you feel a presence inside your mind, an ancient presence.\n\nSuddenly you hear a voice in your mind, \"Welcome Dervishes. I know you have come with many questions and I shall try to answer them all. You are wondering what I am. I will tell you that I am a being called a Crystal Soul.\n\nYou see, when one dies, it is possible that the person be brought back in a crystalline form. Powerful rituals cause the soul actually to assume the shape of a crystal, the shape of perfection.\n\nI am not like those crystals you fought downstairs. They could not truly be called Crystal Souls. They were merely a soul that was infused into a crystal. Although all the magical prowess was maintained, the consciousness was not.\n\nIndeed those crystals were alive, just not sentient like I am. Neither am I human, like the people I serve. I am of an ancient race. We came from another world you see.\n\nAllow me to tell you the tale...", eDialogPic.CREATURE, 124, ["OK"])
        ChoiceBox("Aeons ago, there was a fifth planet where the asteroid belt now lies. The world was quite large and surrounded by thick clouds of Carbon Dioxide. A nearby hot gas planet combined with the atmosphere allowed life to evolve there.\n\nMy species, arose. Their intelligence and prowess allowed the creation of a highly advanced civilization, far more than your world. They could manipulate life and even travel to other planets with their spaceships.\n\nThe closest planet, the fourth, was cold, small and barren. Far too hostile for life to form. However, the third planet, Ermarian, was flourishing with life. At the time, the two major sentient races were the Humans and the Nephilim.\n\nBut then one day, an alien with superior technology came from a star system far away. It began performing experiments on our people and the planet. Although it tried to stay hidden, our people detected it and fought against it.\n\nThe war raged on, but we were no match for the alien\'s technology. In the dark hours, my ancestors managed to turn the technology against the alien and defeated it. The alien was presumably destroyed, but at a terrible cost.\n\nDuring the war, the alien extracted large amounts of energy from the planetary core, destabilizing it. The planet was ravaged by volcanoes and quakes and was torn apart. The homeworld, becoming the asteroid belt was no more.", eDialogPic.CREATURE, 81, ["OK"])
        ChoiceBox("The lone survivors were a sizable group stationed on Ermarian to study it. Being from an always cloudy world, they lived in underground bunkers. Sunlight had an adverse effect on their skin.\n\nRealizing they could never return home, they revealed themselves to the inhabitants and began to share their technology with them. However, they did not realize how savage these two races really were.\n\nBefore they would fight with stones, spears, archery, and even some weak magic. Now they had much more advanced techniques such as shaping metals and powerful magic. With these, the leaders of the tribes could finally eliminate their enemies forever.\n\nThe Humans and Nephilim fought for many years. In the aftermath, the most powerful Nephilim mages were hunted down and slaughtered. The Nephilim dispersed and surrendered to the humans. The survivors were forced into slavery.\n\nRealizing their horrible mistake, my people knew if they stayed on the surface the savages would turn on them. They would kill their benefactors, and then destroy themselves. They knew about a large system of caves beneath the surface.\n\nBeing that the surface environment was hostile to them anyway, they decided to relocate to the caves taking their technologies with them.", eDialogPic.STANDARD, 1027, ["OK"])
        ChoiceBox("Before they left, they resolved one matter. There was a tribe of Humans and Nephilim who remained pacifists. They had the wisdom to see the good advancements that my people\'s technology could bring.\n\nThe Nephilim of the tribe were already enslaved or killed by this time, but the Humans still remained. My people knew that from the tribe\'s peaceful nature, it would be wiped out by the savages if no means were taken to protect it.\n\nSo they created me, a Crystal Soul who would remain with the pacifists forever to guide and protect them. In the years that followed, I was able to dissuade the savage leaders from attacking through psychic influence.\n\nI was able to impart on the pacifists skills and the knowledge to make products that could be used to bargain with the savages. Additionally, I was able to instill a fear that the pacifists were protected by the gods and more powerful than they were.\n\nAfter the formation of the Empire, no one dared attack the pacifists, now called Gynai. I was able to convince the first Emperor Sol I to sign a treaty to preempt possible attacks.\n\nThe fear from the myths about Gynai allowed it to remain safe, and isolated, from the rest of the world. Now you understand where I am from, and now you shall be able to understand what I am to tell you.", eDialogPic.CREATURE, 1028, ["OK"])
        ChoiceBox("My people are still alive today, living deep within the caverns of Avernum. One of them, named Altrus, came to see me recently to ask for knowledge. He wanted to know about the system of energy nodes and ley-lines.\n\nYou see, the planet has a life force of its own. This energy is forever in cycle, much like a system of streams. Ley-lines are the rivers which the energy flows and nodes are like the pools where they intersect.\n\nThis flow of energy allows all things living to be. For with no energy, nothing could exist. Not seeing the potential harm in this, I gave him the knowledge he sought. I did not look deep into his intentions as I should have.\n\nAltrus met with me on several other occasions asking me about the physics of the dark metal you were wondering about. All of this knowledge was provided to him, but I continued to watch.\n\nThroughout the world, he, with the assistance of other mages, built several machines on some of the node sites I had provided. You discovered one of those machines in the old Nephilim temple, which is also a major node.\n\nAt first I thought they were just a method to harvest magical energy. However, a further examination reveals that this cannot be true. I do not know exactly what Altrus means to do, but I can tell his intentions are destructive and must be stopped.", eDialogPic.STANDARD, 1028, ["OK"])
        ChoiceBox("Altrus built a total of four machines at key locations on Pralgad. There are many others on other continents, eighteen in all. You have already found one of the machines at the Nephilim temple.\n\nAnother machine is located high up in the Mandahl Mountains. It was built inside one of the original observation bunkers of the my people. It is quite isolated and difficult to reach.\n\nOne machine is located to the southwest of here in the Stolgrad forest. A brilliant mage named Argadon, long dead, discovered the energy node and built an underground lab there. Altrus built a machine in Argadon\'s old lab.\n\nAnother machine is not far from here, just to the east. It lies within the western portion of the Nelon Mountains in an ancient mine. The mine was cleaned out long ago by the Empire and was abandoned. That is where the other machine is built.\n\nAll of these are suitable locations, they are isolated and on major energy nodes. However, Altrus is drawing close to completing his plans. The machines are well defended, and your Empire is not advanced enough to destroy, or disarm them.\n\nAltrus must be stopped at his source. He has built a final device that will act as a trigger for all the other machines. You must go to...\" The crystal flashes and grows dark!", eDialogPic.STANDARD, 1026, ["OK"])
        Town.PlaceEncounterGroup(1)
        Animation_Explosion(Location(16,18), 2, "005_explosion")
        Animation_Hold()
        Wait()
        ChoiceBox("You turn around to see the Archelder accompanied by a large number of Gynai soldiers, all armed and ready to attack. You are definitely overpowered. None of them look very pleased at you.\n\n\"Well, well, our Empire friends decided to go even further into our sanctuary to probe our secrets. Do you know that you are in violation of our nations\' oldest and most sacred treaty?\n\nNormally, we would treat such dissidents with the punishment of death. However, you are our guests and Empire Dervishes besides. It would not be in our best interests to have you disposed of.\n\nSo, by my decree you are banished forever from Gynai. Soldiers! Escort them to the city gates and revoke their passes. Let us hope this incursion does not occur again, for next time I will not be so forgiving.\"\n\nGiven no choice, you are led away.", eDialogPic.CREATURE, 1028, ["OK"])
        ChoiceBox("As you are led back to the city gates, you reflect back on what you have learned. An alien from a race far below the surface, Altrus, has come to the surface for some destructive purpose. He is building strange machines on the worlds energy nodes.\n\nSomehow these machines involve \'dark metal\' which has destructive and decay properties. Exactly what these machines do remains a mystery. However, you know the locations of three others:\n\nOne is hidden in an ancient bunker high in the Mandahl Mountains. Another is located in an ancient laboratory which can be found in the Stolgrad forest. The other is located in an abandoned mine in the Nelon Mountains.\n\nYou know that by going to these places, you will not be able to stop Altrus. However, it may be possible to learn something more about where the trigger device the Crystal Soul spoke of before he was cut off.\n\nIf only he had been allowed to say one more sentence! But, you must make do with what you have got. You came in here not expecting to learn much, and you definitely have something to go on.\n\nFinally, you reach the gates and your passes are taken from you. The gates slam shut, never again will you be able to visit Gynai without risking your lives. It is time to report what you learned to the Prime Director.", eDialogPic.CREATURE, 124, ["OK"])
        TownMap.List["ArgadonsLab_66"].Hidden = False
        TownMap.List["FloodedMine_67"].Hidden = False
        TownMap.List["AlienBunker_68"].Hidden = False
        StuffDone["100_0"] = 7
        StuffDone["100_1"] = 1
        if Game.Mode != eMode.TOWN or p.Origin != eCallOrigin.MOVING:
            p.CancelAction = True
            return
        Animation_FadeDown()
        Wait()
        Party.Pos = Location(6,32)
        Party.MoveToMap(TownMap.List["Gynai_54"])
        return

def TerrainTypeStepOn_Mist_Aerie_2904(p):
    return
