
def Restock_Shop_Priest_0_26(shop):
    shop.Clear()
    shop.AddSpell("p_cure_all_poison")
    shop.AddSpell("p_curse_all")
    shop.AddSpell("p_dispel_undead")
    shop.AddSpell("p_remove_curse")
    shop.AddSpell("p_sticks_to_snakes")
    shop.AddSpell("p_martyrs_shield")
    shop.AddSpell("p_cleanse")
    shop.AddSpell("p_firewalk")

def Restock_Shop_Items_0_36(shop):
    shop.Clear()
    shop.AddItem(Item.List["BronzeKnife_37"].Copy(True), False)
    shop.AddItem(Item.List["BronzeShortSword_38"].Copy(True), False)
    shop.AddItem(Item.List["BronzeClub_39"].Copy(True), False)
    shop.AddItem(Item.List["BronzeMace_40"].Copy(True), False)
    shop.AddItem(Item.List["BronzeAxe_41"].Copy(True), False)
    shop.AddItem(Item.List["BronzeSpear_42"].Copy(True), False)
    shop.AddItem(Item.List["BronzeHammer_43"].Copy(True), False)
    shop.AddItem(Item.List["BronzeRapier_44"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBroadsword_45"].Copy(True), False)
    shop.AddItem(Item.List["BronzeFlail_46"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBardiche_47"].Copy(True), False)
    shop.AddItem(Item.List["BronzeHalberd_48"].Copy(True), False)
    shop.AddItem(Item.List["BronzeGreatsword_49"].Copy(True), False)
    shop.AddItem(Item.List["BronzeGreatMace_50"].Copy(True), False)
    shop.AddItem(Item.List["IronKnife_51"].Copy(True), False)
    shop.AddItem(Item.List["IronShortSword_52"].Copy(True), False)
