
def RoyalSector_514_MapTrigger_24_43(p):
    MessageBox("Two Cat Paws guard the stairways. They politely block your way. \"Yourr prresence is requested in the Mayorr?s Office.\" they purr.")

def RoyalSector_516_MapTrigger_25_9(p):
    ChoiceBox("Rows of chairs have been set up to witness a turning point in the history of Chimney. Nobles and notabilities from the entire country whisper in agitation.\n\nYou nod at several of the dignitaries. Verundis is here, and mother Priscilla. Lord Harfloot converses the new slith ambassador. At the back of the crowd, you notice Karolynna and Spencer.\n\nMayor Ottar is nowhere in sight, nor are any of his supporters.\n\nWhen you are in place, the crowd goes silent. Commander Groul enters the room and walks up to the Mayor?s Throne.", eDialogPic.TERRAIN, 144, ["OK"])
    Town.PlaceEncounterGroup(2)
    result = ChoiceBox("Groul speaks. \"Citizens of Chimney! I have called you here today to make a momentous decision. We have won a war, but our situation is still dangerous! Our army is shattered and Mayor Ottar has revealed himself to be utterly unfit for ruling Chimney.\n\n\"Some say he was actually in league with the Yvoss-tai, that he hoped for an alliance with them. I don?t know if they are right, nor do I bother to speculate. His actions speak for themselves.\n\n\"Ottar ignored the warnings of an attack. When the sliths struck, he refused to take action. If not for the efforts of the Brattaskar Heroes, we would have been cut off from Exile. And when he did counter the threat, it was too late and too weakly.\n\n\"We all know the result. One thousand citizens lost, the north plundered. On top of this, he banished me and my Cat Paws from court. He refused us to help!\n\n\"Chimney needs a new Mayor! If you wish, I put myself and my Cat Paws at your disposal, to serve and protect Chimney from all enemies. What is your decision?\"\n\nThis is your cue. With your popularity added to Groul?s, no one can stand against you. Yet, doubt gnaws at you. Groul has his own agenda as ruler of Chimney. Do you support Commander Groul as Mayor of Chimney?", eDialogPic.CREATURE, 1024, ["No", "Yes"])
    if result == 0:
        ChoiceBox("You step forward to address the crowd. \"Commander Groul is not fit to rule Chimney!\" You declare loudly. The crowd roars with surprise. \"He has come into his position by crime and deceit!\"\n\nYou hear Groul snarl behind you, and the guards move in. This accusation demands solid evidence. You hope your case is strong enough.", eDialogPic.STANDARD, 17, ["OK"])
        if SpecialItem.PartyHas("ZahrsRobe"):
            MessageBox("\"Groul caused this war! He helped creating the Yvoss-tai cult, posing for Sss-Chross as Zahr, the Masked Aide. He made the sliths believe they were on a holy crusade and had them attack us. They crushed the human army so he could enter as saviour!\n\nYou hold up Zahr?s robe. \"Ambassador, do you recognize this garment? We found it in Groul?s chambers!\" The slith gasps in bafflement. He knows the costume of the God of True Warriors. The crowd whispers in surprise.")
            StuffDone["299_0"] += 1
            if StuffDone["299_0"] == 250:
                pass
            if SpecialItem.PartyHas("BillofSale"):
                MessageBox("\"Groul planned that the sliths should block the Brattaskar Pass! In fact, he provided the Yvoss-tai with the artifact Thunder Rock. He wanted to act alone after the slith war, without influence from Exile. Only chance saved us from being at his mercy!\"\n\nYou hold your Bill of Sale over your heads. \"Verundis, do you acknowledge this document? It proves that you sold the bomb to Groul and gave it to the sliths!\" The silence of the Vahnatai is answer good enough for the shocked audience.")
                StuffDone["299_0"] += 1
                if StuffDone["299_0"] == 250:
                    pass
                if SpecialItem.PartyHas("RashtarrasLamp"):
                    MessageBox("You rub Rashtarra?s Lamp. He emerges in a puff of smoke and tells the story of how Groul found his lamp and the use he made of Rashtarra and his servants. When he comes to the destruction of Whitstone, the audience shudder in disbelief.\n\nKarolynna arises to confirm your story, but her words are soon drowned out by the exclamations of the crowd. Groul shifts restlessly under the accusing glare of his former servant.")
                    StuffDone["299_0"] += 1
                    if StuffDone["299_0"] == 250:
                        pass
                    if StuffDone["299_0"] >= 3:
                        ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
                        MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                        Party.GiveNewItem("ArmsofChimney_394")
                        Scenario.End()
                        return
                    ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
                    RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
                    RunScript("Loopback_19_2", p)
                    return
                if StuffDone["299_0"] >= 3:
                    ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
                    MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                    Party.GiveNewItem("ArmsofChimney_394")
                    Scenario.End()
                    return
                ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
                RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
                RunScript("Loopback_19_2", p)
                return
            if SpecialItem.PartyHas("RashtarrasLamp"):
                MessageBox("You rub Rashtarra?s Lamp. He emerges in a puff of smoke and tells the story of how Groul found his lamp and the use he made of Rashtarra and his servants. When he comes to the destruction of Whitstone, the audience shudder in disbelief.\n\nKarolynna arises to confirm your story, but her words are soon drowned out by the exclamations of the crowd. Groul shifts restlessly under the accusing glare of his former servant.")
                StuffDone["299_0"] += 1
                if StuffDone["299_0"] == 250:
                    pass
                if StuffDone["299_0"] >= 3:
                    ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
                    MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                    Party.GiveNewItem("ArmsofChimney_394")
                    Scenario.End()
                    return
                ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
                RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
                RunScript("Loopback_19_2", p)
                return
            if StuffDone["299_0"] >= 3:
                ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
                MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                Party.GiveNewItem("ArmsofChimney_394")
                Scenario.End()
                return
            ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
            RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
            RunScript("Loopback_19_2", p)
            return
        if SpecialItem.PartyHas("BillofSale"):
            MessageBox("\"Groul planned that the sliths should block the Brattaskar Pass! In fact, he provided the Yvoss-tai with the artifact Thunder Rock. He wanted to act alone after the slith war, without influence from Exile. Only chance saved us from being at his mercy!\"\n\nYou hold your Bill of Sale over your heads. \"Verundis, do you acknowledge this document? It proves that you sold the bomb to Groul and gave it to the sliths!\" The silence of the Vahnatai is answer good enough for the shocked audience.")
            StuffDone["299_0"] += 1
            if StuffDone["299_0"] == 250:
                pass
            if SpecialItem.PartyHas("RashtarrasLamp"):
                MessageBox("You rub Rashtarra?s Lamp. He emerges in a puff of smoke and tells the story of how Groul found his lamp and the use he made of Rashtarra and his servants. When he comes to the destruction of Whitstone, the audience shudder in disbelief.\n\nKarolynna arises to confirm your story, but her words are soon drowned out by the exclamations of the crowd. Groul shifts restlessly under the accusing glare of his former servant.")
                StuffDone["299_0"] += 1
                if StuffDone["299_0"] == 250:
                    pass
                if StuffDone["299_0"] >= 3:
                    ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
                    MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                    Party.GiveNewItem("ArmsofChimney_394")
                    Scenario.End()
                    return
                ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
                RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
                RunScript("Loopback_19_2", p)
                return
            if StuffDone["299_0"] >= 3:
                ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
                MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                Party.GiveNewItem("ArmsofChimney_394")
                Scenario.End()
                return
            ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
            RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
            RunScript("Loopback_19_2", p)
            return
        if SpecialItem.PartyHas("RashtarrasLamp"):
            MessageBox("You rub Rashtarra?s Lamp. He emerges in a puff of smoke and tells the story of how Groul found his lamp and the use he made of Rashtarra and his servants. When he comes to the destruction of Whitstone, the audience shudder in disbelief.\n\nKarolynna arises to confirm your story, but her words are soon drowned out by the exclamations of the crowd. Groul shifts restlessly under the accusing glare of his former servant.")
            StuffDone["299_0"] += 1
            if StuffDone["299_0"] == 250:
                pass
            if StuffDone["299_0"] >= 3:
                ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
                MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                Party.GiveNewItem("ArmsofChimney_394")
                Scenario.End()
                return
            ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
            RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
            RunScript("Loopback_19_2", p)
            return
        if StuffDone["299_0"] >= 3:
            ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
            MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
            Party.GiveNewItem("ArmsofChimney_394")
            Scenario.End()
            return
        ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
        RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
        RunScript("Loopback_19_2", p)
        return
    elif result == 1:
        if StuffDone["213_1"] >= 2:
            if StuffDone["215_0"] >= 1:
                ChoiceBox("You consider the matter for a moment.\n\nYou hold proof that Groul is indeed a criminal. His means are cynical in the extreme. To conquer all of Chimney for Myldres, he used his demon servant to destroy an entire town.\n\nGroul planned this war. Posing as the Masked Aide, he helped Sss-Chross become a mighty leader. He tricked him into attacking Chimney. He even provided them with Thunder Rock, hoping to limit the influence from Exile in his reign after the war.\n\nThere seems to be no limit to what Groul will do to secure his position, nothing is too crude. But, you think, look at what he has accomplished! In ten years, he has ended the bickering of little lordships, nearly stopped the raids of bandits.\n\nTrade flourishes, the population grows, the land is settling down, independent from its powerful neighbours. And, as captain Locke once said, there is peace in Chimney for the first time ever. The peace possible only with a strong, unscrupulous ruler.\n\n\"We back Groul, the saviour of Chimney, as Mayor!\" you announce.", eDialogPic.STANDARD, 1024, ["OK"])
                MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                Party.GiveNewItem("ArmsofChimney_394")
                Scenario.End()
                return
            ChoiceBox("You look uncertainly around the room. Cat Paws line the walls. Between them sit the nobles that supposedly will support Groul. Everyone who might oppose him has been excluded from this meeting.\n\nThey all look at you expectantly. They have heard of the things you have done, they know you are very popular with the common people. They will probably elect Groul no matter what you say, but if you vouch for him, the matter is settled.\n\nYou suspect that electing Groul is a mistake, perhaps even a serious mistake. He has his own agenda, an agenda that might not be favourable to humankind. And you have seen enough of him to know that he will follow his plans unscrupulously.\n\nBut there is nothing you can do. If you had had evidence enough to prove him a criminal, the matter might have been different. All those who support Groul out of fear would have backed you and you could have found a more benign ruler.\n\nYou do not have the evidence, and you dare not defy him with the little evidence you have. So you speak up, and try not to picture a police state run by nephilim in your mind.\n\n\"We back Groul, the saviour of Chimney, as Mayor!\" you announce.", eDialogPic.STANDARD, 1024, ["OK"])
            RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
            if StuffDone["299_0"] >= 3:
                ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
                MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
                Party.GiveNewItem("ArmsofChimney_394")
                Scenario.End()
                return
            ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
            RunScript("Loopback_10_10", p)
            return
        ChoiceBox("You look uncertainly around the room. Cat Paws line the walls. Between them sit the nobles that supposedly will support Groul. Everyone who might oppose him has been excluded from this meeting.\n\nThey all look at you expectantly. They have heard of the things you have done, they know you are very popular with the common people. They will probably elect Groul no matter what you say, but if you vouch for him, the matter is settled.\n\nYou suspect that electing Groul is a mistake, perhaps even a serious mistake. He has his own agenda, an agenda that might not be favourable to humankind. And you have seen enough of him to know that he will follow his plans unscrupulously.\n\nBut there is nothing you can do. If you had had evidence enough to prove him a criminal, the matter might have been different. All those who support Groul out of fear would have backed you and you could have found a more benign ruler.\n\nYou do not have the evidence, and you dare not defy him with the little evidence you have. So you speak up, and try not to picture a police state run by nephilim in your mind.\n\n\"We back Groul, the saviour of Chimney, as Mayor!\" you announce.", eDialogPic.STANDARD, 1024, ["OK"])
        RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
        if StuffDone["299_0"] >= 3:
            ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
            MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
            Party.GiveNewItem("ArmsofChimney_394")
            Scenario.End()
            return
        ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
        RunScript("Loopback_10_10", p)
        return

def RoyalSector_517_MapTrigger_8_12(p):
    if StuffDone["19_0"] == 250:
        return
    StuffDone["19_0"] = 250
    TownMap.List["RoyalSector_19"].DeactivateTrigger(Location(8,12))
    TownMap.List["RoyalSector_19"].DeactivateTrigger(Location(8,13))
    MessageBox("As you enter the sitting room, there is a soft knock on the door. You open, and Commander Groul enters. His whiskers are stiff with excitement on what is to be his great day.")
    Town.PlaceEncounterGroup(1)

def RoyalSector_519_OnEntry(p):
    ChoiceBox("Your journey south is triumphant. Groul?s Cat Paws have wiped out the dispirited slith cultists. They never had time to learn the morale of soldiering, so when they suffered a setback and lost their leaders at the same time, they dissolved at once.\n\nThe threat of slith invasion is gone, but so is most of the human army. Almost one thousand soldiers were lost in the war. And with their ignoble defeats, the prestige of the army was lost.\n\nThe nephilim saved Chimney. Groul is hailed as the saviour on the way south.\n\nBut you share his glory. Everyone has heard how you killed Sss-Chross on the eve of the battle, demoralizing his troops. Stories of your adventures and accomplishments abound, making you almost as grand in their eyes as the Cat Commander himself.\n\nSo when you enter the capital, you ride at the Commander?s side at the head of the column. But your company are far from the first nephilim to arrive in Myldres. You notice that the city gates are guarded by Cat Paws.\n\nYou forget this as a feast is held in your honour in the Great Hall. On the next morning, you bathe and try to clean your clothes, for you know this is an important day. You are summoned to the Mayor?s Office.", eDialogPic.CREATURE, 1024, ["OK"])
    if Game.Mode != eMode.COMBAT:
        Party.Age += 3000
        Party.HealAll(100)
        Party.RestoreSP(100)
def Talking_19_33(p):
    Town.NPCList.Remove(p.NPCTarget)
    if p.NPCTarget.Start.LifeVariable != "":
        StuffDone[p.NPCTarget.Start.LifeVariable] = 1
    p.TalkingText = "\"All popularity must eventually subside, even yours and mine. We need the force to control the crowds when emotions cool down. Today, I will claim the throne of the Mayor.@nIf you vouch for me, all humans will support me. It is your decision. You may support me and take part in my victory, or oppose me and be crushed.\" Groul smiles and leaves."

def Loopback_19_2(p):
    if StuffDone["299_0"] >= 3:
        ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
        MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
        Party.GiveNewItem("ArmsofChimney_394")
        Scenario.End()
        return
    ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
    RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
    RunScript("Loopback_19_2", p)

def Loopback_10_10(p):
    RunScript("GlobalCall_RoyalSector_599", ScriptParameters(eCallOrigin.CUSTOM))
    if StuffDone["299_0"] >= 3:
        ChoiceBox("Your evidence is consistent and overwhelming. One by one, the nobles and notabilities present are convinced by your words, and the chorus of raging voices mounts to a storm.\n\nGroul and his Cat Paw bodyguards pull together, but even his own men are rattled by the scope of Groul?s crimes.\n\nEven now, Groul might have made use of his military advantage to seize control of the city and hold the office by force. This was supposed to be his great day. Groul seems to be considering his options as Rashtarra makes his move.\n\nHe throws himself over Groul, smothering him in his grip, then allows himself to be sucked into his Prison Lamp. Groul goes with him into the plane of demons. Where he belongs, some might add.\n\nActing on impulse, you call for attention in the sudden silence. \"We offer you a good and just Mayor,\" you say, \"one who lives for the good of her fellows and for peace between races. We nominate Karolynna the Priestess!\"\n\nBlushing with surprise, Karolynna stands, to receive the approval of the citizens. She may be inexperienced in politics. Still, you feel that she may be just the kind of ruler a country needs. Once she comes to terms with it herself.", eDialogPic.CREATURE, 1026, ["OK"])
        MessageBox("COMPLETE VICTORY!                               You have acquired a place among the rich and powerful rulers of Chimney. The new Mayor is in office by your effort alone. This insures that your opinion will carry great weight in the Royal Sector.\n\nOn the banquet given in honour of the new Mayor, you are awarded with the famous Arms of Chimney, a rich formal robe carrying the insignia of Chimney. \"A small token of my appreciation\" the newly elected Mayor says and shakes your hands.")
        Party.GiveNewItem("ArmsofChimney_394")
        Scenario.End()
        return
    ChoiceBox("You boldly defy Groul. The audience is shocked by the charges you bring against him, but when they demand more evidence, you stop short. You hold pieces of evidence that imply grave crimes. But far from enough. Facts hint at crimes, but prove little.\n\n\"Enough of this nonsense!\" Groul barks. \"I will hear no more shrill charges. Where is your proof of this?\" You start repeating your charges, but are cut off.\n\n\"I gave you the honour of naming me Mayor out of gratitude. I thought you deserved respect for what you have done. But I now understand that you had your own ambition. You planned to frame me and take the title for yourselves!\"\n\nYou stutter and try to deny the charges. You see Cat Paws move graciously among the rows of dignitaries. They do not threaten, they never even draw any weapons. But the murmur caused by your speech dies out quickly.\n\n\"By rights you deserve death for your treason. But because of your deeds for the country I will spare your lives. Take them away!\" Feline shapes move smoothly around you and lead you out of the room. The election is forgotten, Groul is the leader already.\n\nYou eventually escape prison, and run away from a country that is ruled brutally by the Cat Paw police. At least you tried, you think. At least you resisted. You wish you had been better at it.", eDialogPic.STANDARD, 1024, ["OK"])
    RunScript("Loopback_10_10", p)
