
def Restock_Shop_Items_Outside_25_0_0(shop):
    shop.Clear()
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,1), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,10), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,50), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,1), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,10), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,50), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,1), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,10), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,50), False)

def Restock_Shop_Items_Outside_13_0_1(shop):
    shop.Clear()
    shop.AddItem(Item.List["CrudeBuckler_139"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBuckler_140"].Copy(True), False)
    shop.AddItem(Item.List["IronBuckler_141"].Copy(True), False)
    shop.AddItem(Item.List["SteelBuckler_142"].Copy(True), False)
    shop.AddItem(Item.List["MagicBuckler_143"].Copy(True), False)
    shop.AddItem(Item.List["CrudeShield_144"].Copy(True), False)
    shop.AddItem(Item.List["BronzeShield_145"].Copy(True), False)
    shop.AddItem(Item.List["IronShield_146"].Copy(True), False)
    shop.AddItem(Item.List["SteelShield_147"].Copy(True), False)
    shop.AddItem(Item.List["MagicShield_148"].Copy(True), False)
    shop.AddItem(Item.List["CrudeLargeShield_149"].Copy(True), False)
    shop.AddItem(Item.List["BronzeLargeShield_150"].Copy(True), False)
    shop.AddItem(Item.List["IronLargeShield_151"].Copy(True), False)

def Restock_Shop_Items_Outside_1_2_0(shop):
    shop.Clear()
    shop.AddItem(Item.List["MagicGauntlets_168"].Copy(True), False)
    shop.AddItem(Item.List["Boots_169"].Copy(True), False)
    shop.AddItem(Item.List["SteelToedBoots_170"].Copy(True), False)
    shop.AddItem(Item.List["Lockpicks_171"].Copy(True), False)
    shop.AddItem(Item.List["WeakPoison_172"].Copy(True), False)
    shop.AddItem(Item.List["MediumPoison_173"].Copy(True), False)
    shop.AddItem(Item.List["StrongPoison_174"].Copy(True), False)
    shop.AddItem(Item.List["KillerPoison_175"].Copy(True), False)
    shop.AddItem(Item.List["Ruby_176"].Copy(True), False)
    shop.AddItem(Item.List["Sapphire_177"].Copy(True), False)
    shop.AddItem(Item.List["FineLockpicks_178"].Copy(True), False)
    shop.AddItem(Item.List["MagicLockpicks_179"].Copy(True), False)
    shop.AddItem(Item.List["OrbofSight_180"].Copy(True), False)
    shop.AddItem(Item.List["SmokyCrystal_181"].Copy(True), False)
    shop.AddItem(Item.List["PiercingCrystal_182"].Copy(True), False)

def Restock_Shop_Items_Outside_14_3_1(shop):
    shop.Clear()
    shop.AddItem(Item.List["IronBar_223"].Copy(True), False)

def Restock_Shop_Items_Outside_11_3_2(shop):
    shop.Clear()
    shop.AddItem(Item.List["MediumCuringP_253"].Copy(True), False)
    shop.AddItem(Item.List["MediumHealingP_254"].Copy(True), False)
    shop.AddItem(Item.List["MediumEnergyP_255"].Copy(True), False)
    shop.AddItem(Item.List["MediumStrengthP_256"].Copy(True), False)
    shop.AddItem(Item.List["MediumSpeedP_257"].Copy(True), False)

def Restock_Shop_Mage_0_27(shop):
    shop.Clear()
    shop.AddSpell("m_poison")
    shop.AddSpell("m_ice_bolt")
    shop.AddSpell("m_slow_group")
    shop.AddSpell("m_magic_map")
    shop.AddSpell("m_capture_soul")
    shop.AddSpell("m_simulacrum")
    shop.AddSpell("m_venom_arrows")
    shop.AddSpell("m_wall_of_ice")
    shop.AddSpell("m_stealth")
    shop.AddSpell("m_major_haste")
    shop.AddSpell("m_fire_storm")
    shop.AddSpell("m_dispel_barrier")
    shop.AddSpell("m_fire_barrier")
    shop.AddSpell("m_summoning")
    shop.AddSpell("m_shockstorm")
    shop.AddSpell("m_spray_fields")

def Restock_Shop_Items_1_4(shop):
    shop.Clear()
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,1), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,10), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,50), False)

def Restock_Shop_Items_1_22(shop):
    shop.Clear()
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,1), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,10), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,50), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,1), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,10), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,50), False)

def Restock_Shop_Items_1_40(shop):
    shop.Clear()
    shop.AddItem(Item.List["BronzeKnife_37"].Copy(True), False)
    shop.AddItem(Item.List["BronzeShortSword_38"].Copy(True), False)
    shop.AddItem(Item.List["BronzeClub_39"].Copy(True), False)
    shop.AddItem(Item.List["BronzeMace_40"].Copy(True), False)
    shop.AddItem(Item.List["BronzeAxe_41"].Copy(True), False)
    shop.AddItem(Item.List["BronzeSpear_42"].Copy(True), False)
    shop.AddItem(Item.List["BronzeHammer_43"].Copy(True), False)
    shop.AddItem(Item.List["BronzeRapier_44"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBroadsword_45"].Copy(True), False)
    shop.AddItem(Item.List["BronzeFlail_46"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBardiche_47"].Copy(True), False)
    shop.AddItem(Item.List["BronzeHalberd_48"].Copy(True), False)
    shop.AddItem(Item.List["BronzeGreatsword_49"].Copy(True), False)
    shop.AddItem(Item.List["BronzeGreatMace_50"].Copy(True), False)
    shop.AddItem(Item.List["IronKnife_51"].Copy(True), False)
    shop.AddItem(Item.List["IronShortSword_52"].Copy(True), False)
    shop.AddItem(Item.List["IronMace_53"].Copy(True), False)
    shop.AddItem(Item.List["IronAxe_54"].Copy(True), False)
    shop.AddItem(Item.List["IronSpear_55"].Copy(True), False)
    shop.AddItem(Item.List["IronHammer_56"].Copy(True), False)
    shop.AddItem(Item.List["IronRapier_57"].Copy(True), False)
    shop.AddItem(Item.List["IronBroadsword_58"].Copy(True), False)
    shop.AddItem(Item.List["IronFlail_59"].Copy(True), False)
    shop.AddItem(Item.List["IronBardiche_60"].Copy(True), False)
    shop.AddItem(Item.List["IronHalberd_61"].Copy(True), False)
    shop.AddItem(Item.List["IronGreatsword_62"].Copy(True), False)
    shop.AddItem(Item.List["IronGreatMace_63"].Copy(True), False)
    shop.AddItem(Item.List["SteelKnife_64"].Copy(True), False)
    shop.AddItem(Item.List["SteelShortSword_65"].Copy(True), False)
    shop.AddItem(Item.List["SteelMace_66"].Copy(True), False)

def Restock_Shop_Items_1_47(shop):
    shop.Clear()
    shop.AddItem(Item.List["LeatherBaldric_120"].Copy(True), False)
    shop.AddItem(Item.List["LeatherArmor_121"].Copy(True), False)
    shop.AddItem(Item.List["BronzeStuddedArmor_122"].Copy(True), False)
    shop.AddItem(Item.List["BronzeChainMail_123"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBreastplate_124"].Copy(True), False)
    shop.AddItem(Item.List["BronzePlate_125"].Copy(True), False)
    shop.AddItem(Item.List["IronStuddedArmor_126"].Copy(True), False)
    shop.AddItem(Item.List["IronChainMail_127"].Copy(True), False)
    shop.AddItem(Item.List["IronBreastplate_128"].Copy(True), False)
    shop.AddItem(Item.List["IronPlate_129"].Copy(True), False)
    shop.AddItem(Item.List["SteelStuddedArmor_130"].Copy(True), False)
    shop.AddItem(Item.List["SteelChainMail_131"].Copy(True), False)

def Restock_Shop_Items_1_51(shop):
    shop.Clear()
    shop.AddItem(Item.List["Darts_98"].Copy(True), False)
    shop.AddItem(Item.List["IronDarts_99"].Copy(True), False)
    shop.AddItem(Item.List["MagicDarts_100"].Copy(True), False)
    shop.AddItem(Item.List["ThrowingKnives_101"].Copy(True), False)
    shop.AddItem(Item.List["IronThrowingKnives_102"].Copy(True), False)
    shop.AddItem(Item.List["Arrows_103"].Copy(True), False)
    shop.AddItem(Item.List["IronArrows_104"].Copy(True), False)

def Restock_Shop_Items_1_52(shop):
    shop.Clear()
    shop.AddItem(Item.List["CavewoodBow_108"].Copy(True), False)
    shop.AddItem(Item.List["LemonwoodBow_109"].Copy(True), False)
    shop.AddItem(Item.List["YewBow_110"].Copy(True), False)

def Restock_Shop_Items_1_53(shop):
    shop.Clear()
    shop.AddItem(Item.List["Bolts_115"].Copy(True), False)
    shop.AddItem(Item.List["IronBolts_116"].Copy(True), False)

def Restock_Shop_Items_3_1(shop):
    shop.Clear()
    shop.AddItem(Item.List["Holly_363"].Copy(True), False)
    shop.AddItem(Item.List["ComfreyRoot_364"].Copy(True), False)

def Restock_Shop_Items_3_2(shop):
    shop.Clear()
    shop.AddItem(Item.List["WeakCuringP_260"].Copy(True), False)
    shop.AddItem(Item.List["WeakHealingP_261"].Copy(True), False)
    shop.AddItem(Item.List["WeakEnergyP_262"].Copy(True), False)
    shop.AddItem(Item.List["WeakStrengthP_263"].Copy(True), False)
    shop.AddItem(Item.List["WeakSpeedP_264"].Copy(True), False)

def Restock_Shop_Alchemy_3_3(shop):
    shop.Clear()
    shop.AddRecipe("weak_curing")
    shop.AddRecipe("weak_healing")
    shop.AddRecipe("weak_poison")
    shop.AddRecipe("weak_speed")
    shop.AddRecipe("medium_poison")
    shop.AddRecipe("medium_healing_potion")

def Restock_Shop_Priest_3_17(shop):
    shop.Clear()
    shop.AddSpell("p_cure_all_poison")
    shop.AddSpell("p_curse_all")
    shop.AddSpell("p_dispel_undead")
    shop.AddSpell("p_remove_curse")
    shop.AddSpell("p_sticks_to_snakes")
    shop.AddSpell("p_martyrs_shield")
    shop.AddSpell("p_cleanse")
    shop.AddSpell("p_firewalk")
    shop.AddSpell("p_bless_party")
    shop.AddSpell("p_major_heal")
    shop.AddSpell("p_raise_dead")
    shop.AddSpell("p_flamestrike")
    shop.AddSpell("p_mass_sanctuary")
    shop.AddSpell("p_summon_host")
    shop.AddSpell("p_shatter")
    shop.AddSpell("p_dispel_fields")

def Restock_Shop_Alchemy_5_24(shop):
    shop.Clear()
    shop.AddRecipe("weak_poison")
    shop.AddRecipe("weak_speed")
    shop.AddRecipe("medium_poison")
    shop.AddRecipe("medium_healing_potion")
    shop.AddRecipe("strong_curing_potion")

def Restock_Shop_Items_5_41(shop):
    shop.Clear()
    shop.AddItem(Item.List["Boots_169"].Copy(True), False)
    shop.AddItem(Item.List["SteelToedBoots_170"].Copy(True), False)
    shop.AddItem(Item.List["Lockpicks_171"].Copy(True), False)
    shop.AddItem(Item.List["WeakPoison_172"].Copy(True), False)
    shop.AddItem(Item.List["MediumPoison_173"].Copy(True), False)
    shop.AddItem(Item.List["StrongPoison_174"].Copy(True), False)
    shop.AddItem(Item.List["KillerPoison_175"].Copy(True), False)
    shop.AddItem(Item.List["Ruby_176"].Copy(True), False)
    shop.AddItem(Item.List["Sapphire_177"].Copy(True), False)
    shop.AddItem(Item.List["FineLockpicks_178"].Copy(True), False)

def Restock_Shop_Items_5_43(shop):
    shop.Clear()
    shop.AddItem(Item.List["Candle_17"].Copy(True), False)
    shop.AddItem(Item.List["Lamp_18"].Copy(True), False)

def Restock_Shop_Items_6_6(shop):
    shop.Clear()
    shop.AddItem(Item.List["ScrollFlame_196"].Copy(True), False)
    shop.AddItem(Item.List["ScrollSlow_197"].Copy(True), False)
    shop.AddItem(Item.List["ScrollPoison_198"].Copy(True), False)
    shop.AddItem(Item.List["ScrollStealth_199"].Copy(True), False)

def Restock_Shop_Items_6_21(shop):
    shop.Clear()
    shop.AddItem(Item.List["SteelStuddedArmor_130"].Copy(True), False)
    shop.AddItem(Item.List["SteelChainMail_131"].Copy(True), False)
    shop.AddItem(Item.List["SteelBreastplate_132"].Copy(True), False)
    shop.AddItem(Item.List["SteelPlate_133"].Copy(True), False)
    shop.AddItem(Item.List["MagicStuddedArmor_134"].Copy(True), False)

def Restock_Shop_Mage_6_27(shop):
    shop.Clear()
    shop.AddSpell("m_poison")
    shop.AddSpell("m_ice_bolt")
    shop.AddSpell("m_slow_group")
    shop.AddSpell("m_magic_map")
    shop.AddSpell("m_capture_soul")
    shop.AddSpell("m_simulacrum")
    shop.AddSpell("m_venom_arrows")
    shop.AddSpell("m_wall_of_ice")
    shop.AddSpell("m_stealth")
    shop.AddSpell("m_major_haste")
    shop.AddSpell("m_fire_storm")
    shop.AddSpell("m_dispel_barrier")
    shop.AddSpell("m_fire_barrier")
    shop.AddSpell("m_summoning")
    shop.AddSpell("m_shockstorm")
    shop.AddSpell("m_spray_fields")

def Restock_Shop_Items_6_36(shop):
    shop.Clear()
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,1), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,10), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,50), False)

def Restock_Shop_Items_12_1(shop):
    shop.Clear()
    shop.AddItem(Item.List["Arrows_103"].Copy(True), False)
    shop.AddItem(Item.List["IronArrows_104"].Copy(True), False)
    shop.AddItem(Item.List["MagicArrows_105"].Copy(True), False)

def Restock_Shop_Items_12_2(shop):
    shop.Clear()
    shop.AddItem(Item.List["Crossbow_112"].Copy(True), False)
    shop.AddItem(Item.List["FineCrossbow_113"].Copy(True), False)

def Restock_Shop_Items_12_3(shop):
    shop.Clear()
    shop.AddItem(Item.List["Bolts_115"].Copy(True), False)
    shop.AddItem(Item.List["IronBolts_116"].Copy(True), False)

def Restock_Shop_Items_12_11(shop):
    shop.Clear()
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,1), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,10), False)
    shop.AddItem(Item.List["BreadandMeat_1"].Copy(True,50), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,1), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,10), False)
    shop.AddItem(Item.List["GoodSandwich_2"].Copy(True,50), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,1), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,10), False)
    shop.AddItem(Item.List["TastyMushrooms_3"].Copy(True,50), False)

def Restock_Shop_Items_12_15(shop):
    shop.Clear()
    shop.AddItem(Item.List["IronKnife_51"].Copy(True), False)
    shop.AddItem(Item.List["IronShortSword_52"].Copy(True), False)
    shop.AddItem(Item.List["IronMace_53"].Copy(True), False)
    shop.AddItem(Item.List["IronAxe_54"].Copy(True), False)
    shop.AddItem(Item.List["IronSpear_55"].Copy(True), False)
    shop.AddItem(Item.List["IronHammer_56"].Copy(True), False)
    shop.AddItem(Item.List["IronRapier_57"].Copy(True), False)
    shop.AddItem(Item.List["IronBroadsword_58"].Copy(True), False)
    shop.AddItem(Item.List["IronFlail_59"].Copy(True), False)
    shop.AddItem(Item.List["IronBardiche_60"].Copy(True), False)
    shop.AddItem(Item.List["IronHalberd_61"].Copy(True), False)
    shop.AddItem(Item.List["IronGreatsword_62"].Copy(True), False)
    shop.AddItem(Item.List["IronGreatMace_63"].Copy(True), False)

def Restock_Shop_Items_12_16(shop):
    shop.Clear()
    shop.AddItem(Item.List["IronStuddedArmor_126"].Copy(True), False)
    shop.AddItem(Item.List["IronChainMail_127"].Copy(True), False)
    shop.AddItem(Item.List["IronBreastplate_128"].Copy(True), False)
    shop.AddItem(Item.List["IronPlate_129"].Copy(True), False)
