
def Restock_Shop_Mage_0_15(shop):
    shop.Clear()
    shop.AddSpell("m_poison")
    shop.AddSpell("m_ice_bolt")
    shop.AddSpell("m_slow_group")
    shop.AddSpell("m_magic_map")
    shop.AddSpell("m_capture_soul")
    shop.AddSpell("m_simulacrum")
    shop.AddSpell("m_venom_arrows")
    shop.AddSpell("m_wall_of_ice")
    shop.AddSpell("m_stealth")
    shop.AddSpell("m_major_haste")
    shop.AddSpell("m_fire_storm")
    shop.AddSpell("m_dispel_barrier")
    shop.AddSpell("m_fire_barrier")
    shop.AddSpell("m_summoning")
    shop.AddSpell("m_shockstorm")
    shop.AddSpell("m_spray_fields")
    shop.AddSpell("m_major_poison")
    shop.AddSpell("m_group_fear")
    shop.AddSpell("m_kill")
    shop.AddSpell("m_paralyze")
    shop.AddSpell("m_daemon")
    shop.AddSpell("m_antimagic_cloud")
    shop.AddSpell("m_mindduel")
    shop.AddSpell("m_flight")

def Restock_Shop_Priest_0_25(shop):
    shop.Clear()
    shop.AddSpell("p_cure_all_poison")
    shop.AddSpell("p_curse_all")
    shop.AddSpell("p_dispel_undead")
    shop.AddSpell("p_remove_curse")
    shop.AddSpell("p_sticks_to_snakes")
    shop.AddSpell("p_martyrs_shield")
    shop.AddSpell("p_cleanse")
    shop.AddSpell("p_firewalk")
    shop.AddSpell("p_bless_party")
    shop.AddSpell("p_major_heal")
    shop.AddSpell("p_raise_dead")
    shop.AddSpell("p_flamestrike")
    shop.AddSpell("p_mass_sanctuary")
    shop.AddSpell("p_summon_host")
    shop.AddSpell("p_shatter")
    shop.AddSpell("p_dispel_fields")
    shop.AddSpell("p_heal_all")
    shop.AddSpell("p_revive")
    shop.AddSpell("p_hyperactivity")
    shop.AddSpell("p_destone")
    shop.AddSpell("p_summon_guardian")
    shop.AddSpell("p_mass_charm")
    shop.AddSpell("p_protective_circle")
    shop.AddSpell("p_pestilence")

def Restock_Shop_Alchemy_0_26(shop):
    shop.Clear()
    shop.AddRecipe("medium_speed")
    shop.AddRecipe("graymold_salve")
    shop.AddRecipe("weak_energy_potion")
    shop.AddRecipe("potion_of_clarity")
    shop.AddRecipe("strong_poison")
    shop.AddRecipe("strong_healing_potion")

def Restock_Shop_Items_0_54(shop):
    shop.Clear()

def Restock_Shop_Items_2_11(shop):
    shop.Clear()

def Restock_Shop_Items_8_31(shop):
    shop.Clear()
    shop.AddItem(Item.List["IronRazordisks_96"].Copy(True), False)
    shop.AddItem(Item.List["SteelRazordisks_97"].Copy(True), False)
    shop.AddItem(Item.List["Darts_98"].Copy(True), False)
    shop.AddItem(Item.List["IronDarts_99"].Copy(True), False)
    shop.AddItem(Item.List["MagicDarts_100"].Copy(True), False)
    shop.AddItem(Item.List["ThrowingKnives_101"].Copy(True), False)
    shop.AddItem(Item.List["IronThrowingKnives_102"].Copy(True), False)
    shop.AddItem(Item.List["Arrows_103"].Copy(True), False)
    shop.AddItem(Item.List["IronArrows_104"].Copy(True), False)
    shop.AddItem(Item.List["MagicArrows_105"].Copy(True), False)
    shop.AddItem(Item.List["Javelins_106"].Copy(True), False)
    shop.AddItem(Item.List["IronJavelins_107"].Copy(True), False)

def Restock_Shop_Items_8_32(shop):
    shop.Clear()
    shop.AddItem(Item.List["IronKnife_51"].Copy(True), False)
    shop.AddItem(Item.List["IronShortSword_52"].Copy(True), False)
    shop.AddItem(Item.List["IronMace_53"].Copy(True), False)
    shop.AddItem(Item.List["IronAxe_54"].Copy(True), False)
    shop.AddItem(Item.List["IronSpear_55"].Copy(True), False)
    shop.AddItem(Item.List["IronHammer_56"].Copy(True), False)
    shop.AddItem(Item.List["IronRapier_57"].Copy(True), False)
    shop.AddItem(Item.List["IronBroadsword_58"].Copy(True), False)
    shop.AddItem(Item.List["IronFlail_59"].Copy(True), False)
    shop.AddItem(Item.List["IronBardiche_60"].Copy(True), False)
    shop.AddItem(Item.List["IronHalberd_61"].Copy(True), False)
    shop.AddItem(Item.List["IronGreatsword_62"].Copy(True), False)
    shop.AddItem(Item.List["IronGreatMace_63"].Copy(True), False)
    shop.AddItem(Item.List["SteelKnife_64"].Copy(True), False)
    shop.AddItem(Item.List["SteelShortSword_65"].Copy(True), False)
    shop.AddItem(Item.List["SteelMace_66"].Copy(True), False)
    shop.AddItem(Item.List["SteelAxe_67"].Copy(True), False)
    shop.AddItem(Item.List["SteelSpear_68"].Copy(True), False)
    shop.AddItem(Item.List["SteelHammer_69"].Copy(True), False)
    shop.AddItem(Item.List["SteelRapier_70"].Copy(True), False)
    shop.AddItem(Item.List["SteelBroadsword_71"].Copy(True), False)
    shop.AddItem(Item.List["SteelFlail_72"].Copy(True), False)
    shop.AddItem(Item.List["SteelBardiche_73"].Copy(True), False)
    shop.AddItem(Item.List["SteelHalberd_74"].Copy(True), False)
    shop.AddItem(Item.List["SteelGreatsword_75"].Copy(True), False)
    shop.AddItem(Item.List["SteelGreatMace_76"].Copy(True), False)
    shop.AddItem(Item.List["MagicKnife_77"].Copy(True), False)
    shop.AddItem(Item.List["MagicShortSword_78"].Copy(True), False)
    shop.AddItem(Item.List["MagicMace_79"].Copy(True), False)

def Restock_Shop_Items_8_33(shop):
    shop.Clear()
    shop.AddItem(Item.List["BronzeStuddedArmor_122"].Copy(True), False)
    shop.AddItem(Item.List["BronzeChainMail_123"].Copy(True), False)
    shop.AddItem(Item.List["BronzeBreastplate_124"].Copy(True), False)
    shop.AddItem(Item.List["BronzePlate_125"].Copy(True), False)
    shop.AddItem(Item.List["IronStuddedArmor_126"].Copy(True), False)
    shop.AddItem(Item.List["IronChainMail_127"].Copy(True), False)
    shop.AddItem(Item.List["IronBreastplate_128"].Copy(True), False)
    shop.AddItem(Item.List["IronPlate_129"].Copy(True), False)
    shop.AddItem(Item.List["SteelStuddedArmor_130"].Copy(True), False)
    shop.AddItem(Item.List["SteelChainMail_131"].Copy(True), False)
    shop.AddItem(Item.List["SteelBreastplate_132"].Copy(True), False)
    shop.AddItem(Item.List["SteelPlate_133"].Copy(True), False)
    shop.AddItem(Item.List["MagicStuddedArmor_134"].Copy(True), False)
    shop.AddItem(Item.List["MagicChainMail_135"].Copy(True), False)

def Restock_Shop_Items_8_34(shop):
    shop.Clear()
    shop.AddItem(Item.List["Boots_169"].Copy(True), False)
    shop.AddItem(Item.List["SteelToedBoots_170"].Copy(True), False)
    shop.AddItem(Item.List["Lockpicks_171"].Copy(True), False)
    shop.AddItem(Item.List["WeakPoison_172"].Copy(True), False)
    shop.AddItem(Item.List["MediumPoison_173"].Copy(True), False)
    shop.AddItem(Item.List["StrongPoison_174"].Copy(True), False)
    shop.AddItem(Item.List["KillerPoison_175"].Copy(True), False)
    shop.AddItem(Item.List["Ruby_176"].Copy(True), False)
    shop.AddItem(Item.List["Sapphire_177"].Copy(True), False)
    shop.AddItem(Item.List["FineLockpicks_178"].Copy(True), False)
    shop.AddItem(Item.List["MagicLockpicks_179"].Copy(True), False)
    shop.AddItem(Item.List["OrbofSight_180"].Copy(True), False)
    shop.AddItem(Item.List["SmokyCrystal_181"].Copy(True), False)
    shop.AddItem(Item.List["PiercingCrystal_182"].Copy(True), False)

def Restock_Shop_Items_8_35(shop):
    shop.Clear()
    shop.AddItem(Item.List["MediumCuringP_253"].Copy(True), False)
    shop.AddItem(Item.List["MediumHealingP_254"].Copy(True), False)
    shop.AddItem(Item.List["MediumEnergyP_255"].Copy(True), False)
    shop.AddItem(Item.List["MediumStrengthP_256"].Copy(True), False)
    shop.AddItem(Item.List["MediumSpeedP_257"].Copy(True), False)
    shop.AddItem(Item.List["MediumInvulnP_258"].Copy(True), False)
    shop.AddItem(Item.List["MediumSkillP_259"].Copy(True), False)
    shop.AddItem(Item.List["WeakCuringP_260"].Copy(True), False)
    shop.AddItem(Item.List["WeakHealingP_261"].Copy(True), False)
    shop.AddItem(Item.List["WeakEnergyP_262"].Copy(True), False)
    shop.AddItem(Item.List["WeakStrengthP_263"].Copy(True), False)
    shop.AddItem(Item.List["WeakSpeedP_264"].Copy(True), False)
    shop.AddItem(Item.List["WeakInvulnP_265"].Copy(True), False)
    shop.AddItem(Item.List["WeakSkillP_266"].Copy(True), False)

def Restock_Shop_Items_8_37(shop):
    shop.Clear()
    shop.AddItem(Item.List["WormMeat_386"].Copy(True,1), False)
    shop.AddItem(Item.List["WormMeat_386"].Copy(True,10), False)
    shop.AddItem(Item.List["WormMeat_386"].Copy(True,50), False)

def Restock_Shop_Items_13_5(shop):
    shop.Clear()
    shop.AddItem(Item.List["SteelBroadsword_71"].Copy(True), False)
    shop.AddItem(Item.List["SteelFlail_72"].Copy(True), False)
    shop.AddItem(Item.List["SteelBardiche_73"].Copy(True), False)
    shop.AddItem(Item.List["SteelHalberd_74"].Copy(True), False)
    shop.AddItem(Item.List["SteelGreatsword_75"].Copy(True), False)
    shop.AddItem(Item.List["SteelGreatMace_76"].Copy(True), False)
    shop.AddItem(Item.List["MagicKnife_77"].Copy(True), False)
    shop.AddItem(Item.List["MagicShortSword_78"].Copy(True), False)
    shop.AddItem(Item.List["MagicMace_79"].Copy(True), False)
    shop.AddItem(Item.List["MagicAxe_80"].Copy(True), False)
    shop.AddItem(Item.List["MagicSpear_81"].Copy(True), False)
    shop.AddItem(Item.List["MagicHammer_82"].Copy(True), False)
    shop.AddItem(Item.List["MagicRapier_83"].Copy(True), False)
    shop.AddItem(Item.List["MagicBroadsword_84"].Copy(True), False)

def Restock_Shop_Items_19_6(shop):
    shop.Clear()

def Restock_Shop_Items_21_10(shop):
    shop.Clear()
